apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-new
  labels:
    app: django
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: amannnnyyyy/django_docker_kubernetes:latest
        ports:
        - containerPort: 8000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: djangonew
spec:
  selector:
    app: django
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 8000
    nodePort: 31110